### ISSUE TITLE
Replace DC logo with LC one

### ISSUE THREAD

**Issue by mkuzak** [data-lessons/library-webscraping#20]

**Comment by mkuzak** [comment]
this actually requires upgrading the styles

**Comment by weaverbel** [comment]
This will occur when the styles update from the new template coming from @rgaiacs . I need to sort this so will leave this issue open and feel free to nag me @mkuzak

**Comment by drjwbaker** [comment]
This is a more general issue across lessons https://github.com/data-lessons/librarycarpentry/issues/15#issuecomment-306047352

**Comment by rgaiacs** [comment]
@weaverbel @drjwbaker you can use https://github.com/swcarpentry/infra-lessons to create pull request covering the last release of the styles.

**Comment by weaverbel** [comment]
But did I sign off on the template changes @rgaiacs ? It is all now a total blur , sorry.
