### ISSUE TITLE
Include Beautiful Soup instead of Scrapy (or as an add-on)

### ISSUE THREAD

**Issue by weaverbel** [data-lessons/library-webscraping#6]
Should we include some of the info from here to bring into the lesson? Some people think BS is a better Python tool than Scrapy. https://github.com/qut-dmrc/odiq-web-scraping-workshop @ldko @richyvk

There is also this lesson - both developed by @brendam https://github.com/qut-dmrc/web-scraping-intro-workshop

**Comment by laufers** [comment]
When we have done web-scraping here at OU, we introduce BS and highlight Pandas ability to scrap tables from a webpage. Here is the outline of the notebook that was used for that lesson which was adapted from http://rjweiss.github.io/VAM-Python/VAM.html

**Comment by ldko** [comment]
On #7 there is further discussion and [some agreement](https://github.com/data-lessons/library-webscraping/issues/7#issuecomment-305525803) about adapting the lesson to use Beautiful Soup.

**Comment by runderwood** [comment]
See #11 and #12.
